services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile.amd
    # image: ghcr.io/beecave-homelab/gguf-gui-rocm:main 
    container_name: GGUF-GUI
    restart: unless-stopped
    ports:
      - "8501:8501" 
    volumes:
      - .:/app
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      # Workouround to work with AMD RX6600 GPU
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    # To allow AMD GPU access:
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G
    command: ["streamlit", "run", "main.py", "--browser.serverAddress", "0.0.0.0"]